modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = "Links Discord accounts to Minecraft accounts and assigns LuckPerms ranks automatically."

[[dependencies.unitedlink]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.unitedlink]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
